// authentication
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_AS_MEMBER = 'REGISTER_AS_MEMBER'

// navigation
export const SWITCH_TO_NAVIGATOR = 'SWITCH_TO_NAVIGATOR'
export const SWITCH_TO_REGISTER_SCREEN = 'SWITCH_TO_REGISTER_SCREEN'
export const SWITCH_TO_LOGIN_SCREEN = 'SWITCH_TO_LOGIN_SCREEN'