// authentication
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

// navigation
export const SWITCH_TO_NAVIGATOR = 'SWITCH_TO_NAVIGATOR'
export const SWITCH_TO_REGISTER_SCREEN = 'SWITCH_TO_REGISTER_SCREEN'
export const SWITCH_TO_LOGIN_SCREEN = 'SWITCH_TO_LOGIN_SCREEN'
export const SWITCH_TO_SIGN_UP_SCREEN = 'SWITCH_TO_SIGN_UP_SCREEN'